#!/usr/bin/env python3
# Generate a self-contained bf16 L800 gin = base L800 gin + bf16 override.
# main.py parses a single gin file (no --gin_bindings), and gin applies
# last-write-wins within one file, so appending `Trainer.main_module_bf16 = True`
# after the base flips it on. Idempotent.
import pathlib, sys

BASE = pathlib.Path(
    "proposed_2-mmoe_ple/config/generated_m4_seq_len_50pct/m4_aux_light_hstu_50pct_l800.gin"
)
OUT = BASE.with_name("m4_aux_light_hstu_50pct_l800_bf16.gin")
OVERRIDE = "Trainer.main_module_bf16 = True"

def main() -> int:
    if not BASE.exists():
        print(f"[FAIL] base gin not found: {BASE}", file=sys.stderr)
        return 1
    base = BASE.read_text()
    banner = (
        "\n# ---- MI300 bf16 override (generated by docker/rocm/gen_bf16_gin.py) ----\n"
        "# CDNA3 bf16; do NOT edit hstu.py autocast (see docker/rocm/bf16_overlay.gin).\n"
    )
    OUT.write_text(base.rstrip() + "\n" + banner + OVERRIDE + "\n")
    # sanity: exactly one effective bf16 True at the tail
    print(f"[ok] wrote {OUT}")
    print(f"[ok] tail override: {OVERRIDE}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
